### read

GET http://localhost:3003/api/blogs

### create

POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Hello world",
  "author": "Bob",
  "url": "bobsblog.com",
  "likes": 2000
}

### path that doesnt exist

GET http://localhost:3003/does/not/exist

### delete

DELETE http://localhost:3003/api/blogs/64a4a9253604b05811a4eaee
