### read

GET http://localhost:3003/api/blogs

### create

POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhcm9uMSIsImlkIjoiNjRhZTg1ZDc5NTI0OWU5ODEzOGUxNjg3IiwiaWF0IjoxNjkwMDUxNTI0fQ.MLue5W26OdznAdACTcVF66XPxszDjGNvUDMX1nN0Xk8

{
  "title": "asdf",
  "author": "asdfasdf",
  "url": "google.com",
  "likes": 1000,
  "userId": "64ae85d795249e98138e1687"
}

### path that doesnt exist

GET http://localhost:3003/does/not/exist

### delete

DELETE http://localhost:3003/api/blogs/64a8b25c6d8d18772a6d1421
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhcm9uMSIsImlkIjoiNjRhODcxZDFkMGVjMzQ4OTYxMGY4MmVjIiwiaWF0IjoxNjg4Nzc1NDIxfQ.He7VuSTQJ6N5HWGEeTlXs5P8RLnpUrJOS3t4CCsNBBA

### update

PUT http://localhost:3003/api/blogs/64ae865e95249e98138e1697
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhcm9uMSIsImlkIjoiNjRhZTg1ZDc5NTI0OWU5ODEzOGUxNjg3IiwiaWF0IjoxNjg5MTc5Mjg4fQ.rs6JPxPaBckNATyiRKdgOPeEEq56uudmh_o0f7PNCh0

{
  "title": "Hello world",
  "author": "Bob",
  "url": "bobsblog.com",
  "likes": 2000
}

POST http://localhost:3003/api/blogs/64ae865e95249e98138e1697/comments
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhcm9uMSIsImlkIjoiNjRhZTg1ZDc5NTI0OWU5ODEzOGUxNjg3IiwiaWF0IjoxNjkwMDUxNTI0fQ.MLue5W26OdznAdACTcVF66XPxszDjGNvUDMX1nN0Xk8

{
  "content": "My first comment"
}
